### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by sebstepien** [praashie/fl-novation-impulse#1]
Can it please be updated for FL Studio 20.8?
I find that the faders do not work and change value from -94db to -53db which means fader goes all the way down and does not move

**Comment by praashie** [comment]
Yes, I'm still somewhat maintaining this project. I've got several features in progress and I'm considering an entire refactor to make my script as device-agnostic as possible.

Thanks for reporting, I can reproduce the problem. I haven't had much time to make music recently, but I'll take a look at fixing it today.

**Comment by sebstepien** [comment]
Looking forward to receiving an update.
IS this script compatible with HUI firmware update?

**Comment by sebstepien** [comment]
Any updates on this?
